### ISSUE TITLE
RuntimeError: CudnnRNNLegacyBackward is not differentiable twice

### ISSUE THREAD

**Issue by xzhren** [keon/seq2seq-wgan#1]
I run the code but meet this error. How to resolve it ?

> [!] preparing dataset...
de_vocab_size: 103 en_vocab_size: 84
[!] Instantiating models...
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main()
  File "train.py", line 130, in main
    loss_d.backward()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: CudnnRNNLegacyBackward is not differentiable twice

**Comment by TorusHHH** [comment]
I met the error as well, after I set "torch.backends.cudnn.enabled=False", another error raised.
Did you solve it?

**Comment by keon** [comment]
this code is super old... you will be better off just writing it from scratch
